name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false # CAMBIO IMPORTANTE: Ponlo en false temporalmente

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false # Mantenemos esto en false para evitar el error de la v4.0.6

      - name: Install dependencies
        run: |
          gem install bundler -v 2.5.2 # Instalamos una versión de Bundler compatible
          bundle install # Instalamos las gemas manualmente

      - name: Build site
        run: |
          bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
